### ISSUE TITLE
File is corrupt error / unable to load in firefox.

### ISSUE THREAD

**Issue by PlayfulPiano** [conotoium/Youtube-Darkmode#2]
Tried dragging the zip file over and it did not accept it as an extension. Folder wasn't recognized as an addon at all. v132.0.2 browser, win 10

**Comment by conotoium** [comment]
Oh apologies
Firefox uses a different method for loading extensions than chrome because it uses a different software as its base.
I will quickly spin up a different version with support for Firefox.

**Comment by conotoium** [comment]
I have just submitted the extension to Mozilla(Firefox) in order to get it listed on the add-ons site. Any extensions for Mozilla require them signing off on it to say it is suitable. Once this is completed I will let you know.

**Comment by conotoium** [comment]
Ok this has been resolved with an official mozilla addon page available - https://addons.mozilla.org/en-US/firefox/addon/youtube-dark-mode-override/
